### ISSUE TITLE
Are there any scripts for mpv media player in windows?

### ISSUE THREAD

**Issue by candrapersada** [Kajal4414/Scripts#1]

**Comment by Kajal4414** [comment]
> _No description provided._

For Installation ?

**Comment by candrapersada** [comment]
yes for Installation and auto set PATH environment variable

**Comment by Kajal4414** [comment]
> yes for Installation and auto set PATH environment variable

```ps1
irm https://raw.githubusercontent.com/Kajal4414/Scripts/dev/Windows/Software/mpv.ps1 | iex
```
try this

**Comment by candrapersada** [comment]
```
PS C:\Windows\system32> irm https://raw.githubusercontent.com/Kajal4414/Scripts/dev/Windows/Software/mpv.ps1 | iex      Downloading mpv...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   671    0   671    0     0   1444      0 --:--:-- --:--:-- --:--:--  1449
100   425  100   425    0     0    386      0  0:00:01  0:00:01 --:--:--   386
100 31.1M  100 31.1M    0     0  4830k      0  0:00:06  0:00:06 --:--:-- 5967k
Download successful.
Installing mpv...
Error: The term 'nanazipg' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Press any key to exit...
```
`C:\Program Files\7-Zip\7z.exe`

**Comment by Kajal4414** [comment]
> ```
> PS C:\Windows\system32> irm https://raw.githubusercontent.com/Kajal4414/Scripts/dev/Windows/Software/mpv.ps1 | iex      Downloading mpv...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   671    0   671    0     0   1444      0 --:--:-- --:--:-- --:--:--  1449
> 100   425  100   425    0     0    386      0  0:00:01  0:00:01 --:--:--   386
> 100 31.1M  100 31.1M    0     0  4830k      0  0:00:06  0:00:06 --:--:-- 5967k
> Download successful.
> Installing mpv...
> Error: The term 'nanazipg' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> Press any key to exit...
> ```
> 
> `C:\Program Files\7-Zip\7z.exe`

re-try

**Comment by candrapersada** [comment]
mpv should be added to the Path environment variable to use mpv from cmd.
`where mpv`

**Comment by Kajal4414** [comment]
```cmd
setx PATH "%PATH%;C:\Program Files\MPV"
```

Run this command and restart the terminal. Then verify using the `where mpv`, `mpv --version` command.

**Comment by candrapersada** [comment]
```
# Test folder
$InstallLocation = "C:\Program Files\MPV"

# To add folder to PATH
 $persistedPath = [Environment]::GetEnvironmentVariable('Path', [EnvironmentVariableTarget]::Machine) -split ';'
   if ($persistedPath -notcontains $InstallLocation) {
       $persistedPath = $persistedPath + $InstallLocation | where { $_ }
       [Environment]::SetEnvironmentVariable('Path', $persistedPath -join ';', [EnvironmentVariableTarget]::Machine)
     }

#To verify if PATH isn't already added
    $envPaths = $env:Path -split ';'
    if ($envPaths -notcontains $InstallLocation) {
        $envPaths = $envPaths + $InstallLocation | where { $_ }
        $env:Path = $envPaths -join ';'
    }
```

**Comment by Kajal4414** [comment]
> ```
> # Test folder
> $InstallLocation = "C:\Program Files\MPV"
> 
> # To add folder to PATH
>  $persistedPath = [Environment]::GetEnvironmentVariable('Path', [EnvironmentVariableTarget]::Machine) -split ';'
>    if ($persistedPath -notcontains $InstallLocation) {
>        $persistedPath = $persistedPath + $InstallLocation | where { $_ }
>        [Environment]::SetEnvironmentVariable('Path', $persistedPath -join ';', [EnvironmentVariableTarget]::Machine)
>      }
> 
> #To verify if PATH isn't already added
>     $envPaths = $env:Path -split ';'
>     if ($envPaths -notcontains $InstallLocation) {
>         $envPaths = $envPaths + $InstallLocation | where { $_ }
>         $env:Path = $envPaths -join ';'
>     }
> ```

But why 15/16 lines of code? If our work is being done with one line `setx PATH "%PATH%;C:\Program Files\MPV"` And your cmds sets the system-wide environment (affects all users) which I don't think is right

**Comment by candrapersada** [comment]
> `setx PATH "%PATH%;C:\Program Files\MPV"`

but automatically there will be duplicate PATH system variables in the user variables like
![image](https://github.com/user-attachments/assets/ca2cd59f-25c1-4ba1-8459-b567f045391a)

**Comment by candrapersada** [comment]
how to create Shortcut mpv from Powershell or cmd?

**Comment by Kajal4414** [comment]
> > `setx PATH "%PATH%;C:\Program Files\MPV"`
> 
> but automatically there will be duplicate PATH system variables in the user variables like ![image](https://private-user-images.githubusercontent.com/36833664/351107119-ca2cd59f-25c1-4ba1-8459-b567f045391a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTM1MjYsIm5iZiI6MTcyMTg5MzIyNiwicGF0aCI6Ii8zNjgzMzY2NC8zNTExMDcxMTktY2EyY2Q1OWYtMjVjMS00YmExLTg0NTktYjU2N2YwNDUzOTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA3NDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMWY1OWIxMWYxODk0ZTVjNzg2MjViZDhkZDBlYTU0Y2NiODliNGQ3YjUzY2M1M2U5NDA2NzgzZGZlNjhjOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iUTCdP8hzbqhUOUZJi1ey3pQR4j5_YaWyOn-IBxTB2E)

I checked my local system, but I couldn't find anything like that. However, if you're facing this issue, you can use the command below. This should remove duplicate paths.

```ps1
[System.Environment]::SetEnvironmentVariable('PATH', (($env:PATH -split ';' | Where-Object { $_ -ne '' } | Sort-Object -Unique) -join ';'), [System.EnvironmentVariableTarget]::User)
```

**Comment by Kajal4414** [comment]
> how to create Shortcut mpv from Powershell or cmd?

```ps1
$sh = (New-Object -ComObject WScript.Shell).CreateShortcut("$env:USERPROFILE\Desktop\MPV.lnk"); $sh.TargetPath = "$env:PROGRAMFILES\MPV\mpv.exe"; $sh.Save()
```

**Comment by candrapersada** [comment]
how to create Shortcut from cmd?
and how to add arguments mpv in Shortcut from cmd?

**Comment by Kajal4414** [comment]
> how to create Shortcut from cmd? and how to add arguments mpv in Shortcut from cmd?

Batch scripts alone do not have built-in capabilities to create Windows shortcuts (`.lnk` files) directly. They can create symbolic links using `mklink`, but these are not the same as shortcuts.

**Comment by candrapersada** [comment]
how to add arguments mpv in Shortcut from powershell?

**Comment by Kajal4414** [comment]
To pass arguments to the target app when creating a shortcut using PowerShell, you can set the `Arguments` property of the shortcut object. See this example:

```ps1
# Create a new shortcut object
$sh = (New-Object -ComObject WScript.Shell).CreateShortcut("$env:USERPROFILE\Desktop\MPV.lnk")

# Set the path to the executable
$sh.TargetPath = "$env:PROGRAMFILES\MPV\mpv.exe"

# Optionally, set the working directory (if needed)
$sh.WorkingDirectory = "$env:PROGRAMFILES\MPV"

# Set any arguments you want to pass to the executable
$sh.Arguments = "--fullscreen --no-audio" # Example arguments

# Save the shortcut
$sh.Save()
```

Replace `--fullscreen --no-audio` with any arguments.

**Comment by candrapersada** [comment]
how to add Shortcut to TaskBar and Start Menu from powershell?

**Comment by Kajal4414** [comment]
> how to add Shortcut to TaskBar and Start Menu from powershell?

Start Menu Shortcut
```ps1
$mpvPath = "$env:PROGRAMFILES\MPV\mpv.exe"; $shortcutPath = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\mpv.lnk"; $wshShell = New-Object -ComObject WScript.Shell; $shortcut = $wshShell.CreateShortcut($shortcutPath); $shortcut.TargetPath = $mpvPath; $shortcut.Save(); Write-Host "Shortcut created in Start Menu:" $shortcutPath
```

Reference for pin to taskbar https://github.com/Atlas-OS/Atlas/blob/main/src/playbook/Executables/TASKBARPINS.cmd

**Comment by candrapersada** [comment]
how to remove duplicate PATH system variables in the user variables like
![image](https://github.com/user-attachments/assets/0c89a87d-064d-41fe-ad7e-e1ec4455a250)

**Comment by Kajal4414** [comment]
> > > `setx PATH "%PATH%;C:\Program Files\MPV"`
> > 
> > 
> > but automatically there will be duplicate PATH system variables in the user variables like ![image](https://private-user-images.githubusercontent.com/36833664/351107119-ca2cd59f-25c1-4ba1-8459-b567f045391a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTM1MjYsIm5iZiI6MTcyMTg5MzIyNiwicGF0aCI6Ii8zNjgzMzY2NC8zNTExMDcxMTktY2EyY2Q1OWYtMjVjMS00YmExLTg0NTktYjU2N2YwNDUzOTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA3NDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMWY1OWIxMWYxODk0ZTVjNzg2MjViZDhkZDBlYTU0Y2NiODliNGQ3YjUzY2M1M2U5NDA2NzgzZGZlNjhjOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iUTCdP8hzbqhUOUZJi1ey3pQR4j5_YaWyOn-IBxTB2E)
> 
> I checked my local system, but I couldn't find anything like that. However, if you're facing this issue, you can use the command below. This should remove duplicate paths.
> 
> ```powershell
> [System.Environment]::SetEnvironmentVariable('PATH', (($env:PATH -split ';' | Where-Object { $_ -ne '' } | Sort-Object -Unique) -join ';'), [System.EnvironmentVariableTarget]::User)
> ```

:roll_eyes:

**Comment by candrapersada** [comment]
but if use `setx PATH "%PATH%;C:\Program Files\MPV"` there are duplicates like this in user variables
without use `setx PATH "%PATH%;C:\Program Files\MPV"`
`C:\Users\username\AppData\Local\Microsoft\WindowsApps`
aftar use `setx PATH "%PATH%;C:\Program Files\MPV"`
`C:\Users\username\AppData\Local\Microsoft\WindowsApps;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files\MPV`
