### ISSUE TITLE
is there any alternative IDM Activation Script 

### ISSUE THREAD

**Issue by candrapersada** [Kajal4414/Scripts#3]
is there any alternative IDM Activation Script without pop up
![image](https://github.com/user-attachments/assets/08ffcec5-df31-43b1-8bb8-5525513badeb)

**Comment by Kajal4414** [comment]
> is there any alternative IDM Activation Script without pop up ![image](https://private-user-images.githubusercontent.com/36833664/361673518-08ffcec5-df31-43b1-8bb8-5525513badeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mzg5MjIsIm5iZiI6MTcyNDczODYyMiwicGF0aCI6Ii8zNjgzMzY2NC8zNjE2NzM1MTgtMDhmZmNlYzUtZGYzMS00M2IxLThiYjgtNTUyNTUxM2JhZGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA2MDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYmNjODUwNjQxYTNmNzE3NDVjMjRiZjg2MzIyZmJjOGRjMjE5YjRiZjNjYjBmY2ViY2QwNTA4NzdjZWUyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3kYhq1f2ZUCqu1FGgmELMeFQhVJjZQzYF7iqMap1fhI)

https://github.com/AliDbg/IDM_Trial_Reset_IAS
Try this.

**Comment by candrapersada** [comment]
Is it true that you can turn off the Idm Trial pop-up?

**Comment by Kajal4414** [comment]
> Is it true that you can turn off the Idm Trial pop-up?

Is the trial popup like the one you showed in the screenshot? I don't know about it; I've never seen it. I used the [IDM trial reset](https://github.com/J2TEAM/idm-trial-reset/releases/tag/v1.0.0) app last month, and I haven't received any popup or registration reminder so far, even though I updated it last week
![Capture](https://github.com/user-attachments/assets/fc0b20b8-1708-43f1-a315-1ecac763029e)
**Note**: Don't use trial reset; instead, choose register and use @ before the name, like @admin.

**Comment by candrapersada** [comment]
![image](https://github.com/user-attachments/assets/15f74c83-3874-4038-9bf4-290d5faa31eb)

**Comment by Kajal4414** [comment]
Probably, the issue is happening because you've used several scripts. First, completely uninstall the software using 'Bulk Crap Uninstaller' or any other uninstaller, then reinstall it. After that, activate it using the tool, and finally, kill the app from Task Manager before reopening it.

**Comment by candrapersada** [comment]
not working
