### ISSUE TITLE
How to use Script to check for latest apps and select apps to update?

### ISSUE THREAD

**Issue by candrapersada** [Kajal4414/Scripts#4]

**Comment by Kajal4414** [comment]
I believe you are referring to the [install_apps.ps1](https://github.com/Kajal4414/Scripts/blob/main/Windows/Software/install_apps.ps1) script. 

First, clone this repository and navigate to its directory. Second, run the [script.ps1](https://github.com/Kajal4414/Scripts/blob/main/.github/scripts/script.ps1) `.\.github\scripts\script.ps1`. This script will retrieve the latest versions of all apps defined within it and update the direct URLs and version information in the [install_apps.json](https://github.com/Kajal4414/Scripts/blob/main/Windows/Software/install_apps.json) file.

After that, run `.\Windows\Software\install_apps.ps1` to install or update applications. If you don't want to install or update any application, simply remove it from the `install_apps.json` file before running the `install_apps.ps1` script."

**Comment by candrapersada** [comment]
what I mean is how to check the old version number of the installed application and the latest version number?
![image](https://github.com/user-attachments/assets/0f7d12d8-9871-4310-a1aa-36d3b4d5749b)
